### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by azlux** [orion-labs/opuslib#16]
Hi,
I try to understand why a simple bot on pymumble eat so much memory when the bot listen users voices.
Here the bot I've write. https://azlux.fr/bin/?2efbca797cb8afd9#9FHCb8xSNXuSihf2728x9u3Jtqns5J6FFGEmMcJpMBaW

There result show me :
```
root@lyoko:~/pymumble$ venv/bin/python3 echobot.py
[ Top 10 ]
/root/pymumble/venv/lib/python3.7/site-packages/opuslib/api/decoder.py:180: size=41.9 MiB, count=22508, average=1953 B
/root/pymumble/pymumble_py3/soundqueue.py:115: size=3015 KiB, count=40373, average=76 B
/root/pymumble/pymumble_py3/soundqueue.py:59: size=1847 KiB, count=45013, average=42 B
/root/pymumble/pymumble_py3/soundoutput.py:61: size=435 KiB, count=18557, average=24 B
/root/pymumble/venv/lib/python3.7/site-packages/opuslib/api/decoder.py:164: size=407 KiB, count=87, average=4786 B
/root/pymumble/pymumble_py3/soundoutput.py:55: size=396 KiB, count=16892, average=24 B
/root/pymumble/pymumble_py3/tools.py:72: size=341 KiB, count=12485, average=28 B
/root/pymumble/pymumble_py3/mumble.py:500: size=336 KiB, count=4676, average=74 B
/root/pymumble/pymumble_py3/tools.py:80: size=239 KiB, count=8725, average=28 B
/root/pymumble/pymumble_py3/soundqueue.py:62: size=181 KiB, count=351, average=528 B
```
Summary point opuslib decoder function.
Can you help on this issue ? (https://github.com/azlux/pymumble/issues/44 and https://github.com/azlux/botamusique/issues/95)

Azlux

**Comment by azlux** [comment]
I'm trying to find the line with memory_profiler
https://azlux.fr/bin/?77fbf5abf231b0b9#5BLzJkw7gWjLWLu6ohjbexNAuybHuUXALMYAVbqeCnhA

this line : `pcm = (ctypes.c_int16 * pcm_size)()` use some memory (0.3Mb/loop), I'm not sure.

**Comment by TerryGeng** [comment]
I confirmed that as long as the api function
https://github.com/orion-labs/opuslib/blob/92109c528f9f6c550df5e5325ca0fcd4f86b0909/opuslib/api/decoder.py#L236
is called, the memory starts to leak. If I commented out this line, everything would be fine.

Is there any leak in the opus?
