### ISSUE TITLE
Windows issue loading opus.dll

### ISSUE THREAD

**Issue by aaknitt** [orion-labs/opuslib#17]
I have followed the instructions on downloading and renaming the opus DLL found [here](https://github.com/discordrb/discordrb/wiki/Installing-libopus).  I have opus.dll in the same file as my Python file and I am _not_ getting the 'Could not find Opus library. Make sure it is installed.' error, so the opus.dll file is being found.  Based on what I found when looking at opus.dll with [this tool](https://github.com/lucasg/Dependencies) I've also put libgcc_s_sjljaa-1.dll (which comes with the opusfile download) in the same directory since it appears it may be needed by opus.dll.

I am now getting this error when opus.dll is trying to be loaded:

Traceback (most recent call last):
  File "C:\Users\username\Python\test2.py", line 5, in <module>
    from opuslib import encoder, decoder
  File "C:\Python37\lib\site-packages\opuslib\__init__.py", line 19, in <module>
    from .exceptions import OpusError  # NOQA
  File "C:\Python37\lib\site-packages\opuslib\exceptions.py", line 10, in <module>
    import opuslib.api.info
  File "C:\Python37\lib\site-packages\opuslib\api\__init__.py", line 24, in <module>
    libopus = ctypes.CDLL(lib_location)
  File "C:\Python37\lib\ctypes\__init__.py", line 365, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 126] The specified module could not be found

It looks like this is likely not an issue with opuslib but any advise on how to resolve would be appreciated.

**Comment by aaknitt** [comment]
Resolved - needed to add some additional DLL files from the opusfile package.  
These DLL files are needed (in the same director as the Python file or elsewhere in the Windows DLL search path):
- opus.dll (renamed from libopus-0.dll)
- libwinpthread-1.dll
- libgcc_s_sjlj-1.dll

These can be obtained from the 'opusfile' download at [http://opus-codec.org/downloads/](http://opus-codec.org/downloads/)

**Comment by CodeDiseaseDev** [comment]
i hate it when c++ library developers release the source code, and then people tell me to go to their downloads page to find the dlls, and theres no dlls, its like "oh they're somewhere, find them..."

**Comment by CodeDiseaseDev** [comment]
wtf? do they not exist

**Comment by LifeXPain2012** [comment]
bro you know about how to built source code into dll file?

**Comment by zn123** [comment]
https://download.csdn.net/download/zhangning/90373207?spm=1001.2014.3001.5503
